### ISSUE TITLE
wrong dependencies

### ISSUE THREAD

**Issue by simo9900** [JonasWanke/timetable#65]
I am adding in my projects the timetable in my pubspec, and I got this error

```
Because no versions of firebase_picture_uploader match >1.2.2 <2.0.0 and firebase_picture_uploader 1.2.2 depends on image ^3.0.1, firebase_picture_uploader ^1.2.2 requires image ^3.0.1.
And because no versions of image match >3.0.1 <4.0.0, firebase_picture_uploader ^1.2.2 requires image 3.0.1.
And because image 3.0.1 depends on archive ^3.0.0 which depends on crypto ^3.0.0, firebase_picture_uploader ^1.2.2 requires crypto ^3.0.0.
And because timetable >=0.2.7 depends on dartx ^0.5.0 which depends on crypto ^2.1.0, firebase_picture_uploader ^1.2.2 is incompatible with timetable >=0.2.7.
So, because remote_students depends on both firebase_picture_uploader ^1.2.2 and timetable ^0.2.8, version solving failed.
pub get failed (1; So, because remote_students depends on both firebase_picture_uploader ^1.2.2 and timetable ^0.2.8, version solving failed.)

```
This is my pubspec.yaml

```
  firebase_picture_uploader: ^1.2.2

  timetable: ^0.2.8
  time_machine: ^0.9.16

dependency_overrides:
  time_machine:
    git:
      url: https://github.com/Dana-Ferguson/time_machine
      ref: 7753e0d

```

I can't use another package lower than firebase_picture_uploader ^1.2.2. Can anyone have an idea how can I solve it?

Thanks
